[[pages]]
path = "main.py"
name = "首页"
icon = "🏠"

[[pages]]
path = "pages/hots.py"
name = "热点库"
icon = "🔥"
url_path = "hots"

[[pages]]
path = "pages/accounts.py"
name = "账号管理"
icon = "👥"
url_path = "accounts"

[[pages]]
path = "pages/tasks.py"
name = "任务中心"
icon = "🧾"
url_path = "tasks"

[[pages]]
path = "pages/my.py"
name = "个人中心"
icon = "👨‍💼"
url_path = "my"


[[pages]]
path = "pages/auto.py"
name = "AI托管"
icon = "🤖"
url_path = "auto"


[[pages]]
path = "pages/exit.py"
name = "退出登录"
icon = "❌"
url_path = "exit"
